name: 🖥️ Windows Builds

on:
  push:
    branches-ignore:
      - "l10n_master"
  pull_request:
    branches:
      - master

jobs:
  # MSBUILD
  lint_vs_proj_files:
    name: Lint VS Project Files
    if: github.repository != 'PCSX2/pcsx2' || github.event_name == 'pull_request'
    runs-on: windows-2025-vs2026
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Verify VS Project Files
        run: .github\workflows\scripts\windows\validate-vs-filters.ps1

  build_qt_avx2:
    needs: lint_vs_proj_files
    name: "AVX2"
    if: github.repository != 'PCSX2/pcsx2' || github.event_name == 'pull_request'
    uses: ./.github/workflows/windows_build_qt.yml
    with:
      jobName: "MSVC AVX2"
      artifactPrefixName: "PCSX2-windows-Qt-x64-avx2-msvc"
      configuration: Release AVX2
    secrets: inherit
